# Generated by Django 5.0.3 on 2024-03-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0002_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="json_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="json_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
