# Generated by Django 5.0.3 on 2024-03-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0003_alter_application_json_data_alter_form_json_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="json_data",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="form",
            old_name="json_data",
            new_name="struct",
        ),
        migrations.AddField(
            model_name="form",
            name="description",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
